[changelog]
header = ""
body = """
{%- for group, commits in commits | group_by(attribute="group") %}
## {{ group }}
{% for commit in commits %}
- {{ commit.message | split(pat="\n") | first | trim }}\
  {% if commit.github.pr_number %} (#{{ commit.github.pr_number }}){% endif %}\
  {% if commit.github.username %} by @{{ commit.github.username }}{% endif %}
{%- endfor %}
{% endfor %}
"""
trim = true

[git]
conventional_commits = false
split_commits = false
commit_parsers = [
  { message = "^cli:", group = "CLI" },
  { message = "^app:", group = "App" },
  { message = "^infra:", group = "Infrastructure" },
  { message = "^site:", group = "Site" },
  { message = "^types:", group = "Types" },
]
filter_commits = true
tag_pattern = "v[0-9].*"

[remote.github]
owner = "tchayen"
repo = "oru"
