name = "oru-telemetry"
main = "src/index.ts"
compatibility_date = "2025-01-01"
workers_dev = false
preview_urls = false

[[d1_databases]]
binding = "DB"
database_name = "oru-telemetry"
database_id = "b8eae1a2-8adb-4fb2-acd6-6c56b8cc35ad"
migrations_dir = "migrations"
